<!DOCTYPE html>
<html>
<head>
    <title>Apocalyptic dates</title>
    <style type="text/css">
        table {
            border-collapse: collapse;
        }
        th, td {
            padding: 4px;
            border: 1px solid grey;
        }
        th {
            text-align: left;
        }
    </style>
</head>

<body>

<h2>Apocalyptic dates</h2>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>

</body>

</html>