<?php if($this->dates && $this->dates->count()): ?>

    <table>
    <tr>
        <th>Date</th>
        <th>Author</th>
        <th>Description</th>
        <th>Happened?</th>
    </tr>
    <?php foreach ($this->dates as $date): ?>
        <tr>
            <td><strong><?php echo $date->date ?></strong></td>
            <td><?php
                $author = $date->findParentRow('Apoc_Model_Author_Table');
                echo $author->name . ' (' . $author->description . ')';
                ?>
            </td>
            <td><?php echo $date->description; ?></td>
            <td><?php echo $date->happened ? 'yes' : 'no' ?></td>
        </tr>
    <?php endforeach; ?>
    </table>

<?php endif; ?>